name: nowcast
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - pillow
  - requests
  - beautifulsoup4
  - h5py
  - pyproj
  - scipy
  - cartopy
  - opencv
  - pip
  - pip:
    - pysteps
    - websocket-client
